### ISSUE TITLE
Multipart messages raw source not shown correctly

### ISSUE THREAD

**Issue by rm--** [transcode-de/correos#4]
Multipart messages raw source is not shown correctly.

---
- Bitbucket: https://bitbucket.org/transcode/correos/issue/4
- Originally reported by: [wrtsprt](https://bitbucket.org/wrtsprt)
- Originally created at: 2014-01-03T14:29:47.745

**Comment by keimlink** [comment]
@rm-- Can you please provide an example?

**Comment by rm--** [comment]
@keimlink No, I can't because I am not the real author of this issue. I only migrated it from bitbucket to github.

**Comment by keimlink** [comment]
Sorry @rm--, forgot you just made the import. 😃

**Comment by keimlink** [comment]
@wrtsprt Can you please give an example for the multipart problem?

**Comment by wrtsprt** [comment]
I can't seem to reproduce this (or actually remember what the concrete problem was). I think we can close this issue. 

 There is another problem with multipart, I made a ticket for that. (#16).

**Comment by keimlink** [comment]
@wrtsprt Thanks for the fast reply! 👍
